name: Purge old branches test
permissions:
  actions: read|write
  checks: read|write
  contents: read|write
  deployments: read|write
  id-token: read|write
  issues: read|write
  discussions: read|write
  packages: read|write
  pages: read|write
  pull-requests: read|write
  repository-projects: read|write
  security-events: read|write
  statuses: read|write
on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Do a dry run first, which won't delete any branches (Recommended)?
        type: choice
        required: true
        default: 'true'
        options:
          - 'yes'
          - 'no'
      daysSinceLastCommit:
        description: Total days since last commit.
        type: string
        required: true
        default: "90"
      branchesToExclude:
        description: Comma separated list of branches to exclude
        type: string
        required: false
        default: "main,master,develop"
jobs:
  purging:
    name: Purge old branches
    runs-on: ubuntu-latest
    steps:
      - name: Run Purge old branches Action
        id: purge-old-branches
        uses: WMadgwickSig/PurgeGitBranches@main
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          dryRun: ${{ github.event.inputs.dryRun }}
          branchesToExclude: ${{ github.event.inputs.branchesToExclude }}
          daysSinceLastCommit: ${{ github.event.inputs.daysSinceLastCommit }}
      - name: Get output
        run: |
          echo 'exception = ${{ steps.purge-old-branches.outputs.exception }}'
          echo 'was-dryrun = ${{ steps.purge-old-branches.outputs.was-dryrun }}'
          echo 'min-days-since-last-commit = ${{ steps.purge-old-branches.outputs.min-days-since-last-commit }}'
          echo 'excluded-branches = ${{ steps.purge-old-branches.outputs.excluded-branches }}'
          echo 'total-branches-purged = ${{ steps.purge-old-branches.outputs.total-branches-purged }}'
          echo 'result-json = ${{ steps.purge-old-branches.outputs.result-json }}'
