name: VersionBump
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number to go to
        type: string
        required: true
        default: "0.0.0"
permissions: write-all
jobs:
  BumpVersion:
      name: Bump Version
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        - name: Bump version
          run:  |
            git pull --rebase origin main
            echo "Repo pulled"
  Output:
    name: Output
    runs-on: ubuntu-latest
    steps:
      - name: Get output
        run: |
          echo 'Version: ${{ github.event.inputs.version }}'
