name: VersionBump
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number to go to
        type: string
        required: true
        default: "0.0.0"
permissions: write-all
jobs:
  BumpVersion:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Extract current version
        id: extract_version
        run: |
          if grep -q '<Version>.*<\/Version>' GithubAction/GithubAction.csproj; then
            echo "version=$(grep -oP '<Version>\K[^<]+' GithubAction/GithubAction.csproj)" >> $GITHUB_OUTPUT
          else
            echo "version=0.0.0" >> $GITHUB_OUTPUT
          fi
      - name: Bump version
        run: |
          current_version=${{ steps.extract_version.outputs.version }}
          new_version=${{ github.event.inputs.version }}
          echo "Current Version: $current_version"
          echo "New Version: $new_version"
          sed -i "s|<Version>.*</Version>|<Version>$new_version</Version>|" "GithubAction/GithubAction.csproj"
          git add -A
          git config --global user.name ${{ github.actor }}
          git commit -m "Bump version to $new_version"
          git pull --rebase origin main
          git push origin main
