name: VersionBump
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number to go to
        type: string
        required: true
        default: "0.0.0"
permissions: write-all
jobs:
  BumpVersion:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Bump version
        run: |
          new_version=${{ github.event.inputs.version }}
          echo "New Version: $new_version"
          sed -i "s|<Version>.*</Version>|<Version>$new_version</Version>|" GithubAction.csproj
          git add GithubAction.csproj
          git commit -m "Bump version to $new_version"
          git push origin main
