name: VersionBump
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number to go to
        type: string
        required: true
        default: ${{ vars.LATEST_VERSION }}
permissions: write-all
jobs:
  BumpVersion:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Bump version
        run: |
          previous_version=$(grep -oP '<Version>\K[^<]+' GithubAction/GithubAction.csproj)
          new_version=${{ github.event.inputs.version }}
          echo "Previous Version: $previous_version"
          echo "New Version: $new_version"
          sed -i "s|<Version>.*</Version>|<Version>$new_version</Version>|" "GithubAction/GithubAction.csproj"
          git add -A
          git config --global user.name ${{ github.actor }}
          git commit -m "Bump version to $new_version"
          git pull --rebase origin main
          git push origin main
